# Generated by Django 4.2.7 on 2025-08-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Supabase-hosted thumbnail URL (auto-generated)'),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_video',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='External or Supabase video URL'),
        ),
    ]
