# Generated by Django 4.2.7 on 2025-08-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video_thumbnail_url_video_upload_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', '-video_created_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
