# Generated by Django 4.2.7 on 2025-08-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_video_options_video_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='decision_maker_contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='decision_maker_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_decision_maker',
        ),
    ]
