# Generated by Django 4.2.7 on 2025-08-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_contact_decision_maker_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceicon',
            name='icon_class',
            field=models.CharField(choices=[('lucide-briefcase', 'Business & Consulting'), ('lucide-code', 'Software Development'), ('lucide-paintbrush', 'Design & Branding'), ('lucide-camera', 'Photography & Videography'), ('lucide-rocket', 'Startup & Innovation'), ('lucide-globe', 'Global Services'), ('lucide-shield', 'Security & Compliance'), ('lucide-lightbulb', 'Creative Ideas'), ('lucide-server', 'Cloud & Hosting'), ('lucide-shopping-cart', 'E-commerce Solutions'), ('lucide-bar-chart', 'Analytics & Marketing'), ('lucide-heart', 'Health & Wellness'), ('lucide-graduation-cap', 'Education & Training'), ('lucide-music', 'Music & Entertainment'), ('lucide-map-pin', 'Location-based Services')], help_text='Select a predefined Lucide icon', max_length=100),
        ),
    ]
