# Generated by Django 5.2.5 on 2025-08-19 15:23

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_serviceicon_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='upload_thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='upload_video',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_file',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
